use std::collections::HashMap;
use std::sync::LazyLock;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Emotion {
    Joy,
    Anger,
    Sadness,
    Fear,
    Surprise,
    Disgust,
}

impl Emotion {
    pub fn as_str(&self) -> &'static str {
        match self {
            Emotion::Joy => "Joy",
            Emotion::Anger => "Anger",
            Emotion::Sadness => "Sadness",
            Emotion::Fear => "Fear",
            Emotion::Surprise => "Surprise",
            Emotion::Disgust => "Disgust",
        }
    }
}

pub static NRC_EMOTIONS: LazyLock<HashMap<&'static str, Vec<Emotion>>> = LazyLock::new(|| {
    use Emotion::*;
    let entries: &[(&str, &[Emotion])] = &[
        // ===== A =====
        ("abandon", &[Fear, Sadness]),
        ("abandoned", &[Anger, Fear, Sadness]),
        ("abandonment", &[Sadness, Fear]),
        ("abhor", &[Anger, Disgust]),
        ("abhorrent", &[Anger, Disgust]),
        ("abominate", &[Disgust, Anger]),
        ("abomination", &[Disgust, Anger, Fear]),
        ("abuse", &[Anger, Fear, Sadness]),
        ("abused", &[Anger, Sadness, Fear]),
        ("abusive", &[Anger, Fear, Disgust]),
        ("accident", &[Fear, Surprise, Sadness]),
        ("accomplish", &[Joy, Surprise]),
        ("accomplishment", &[Joy]),
        ("ache", &[Sadness]),
        ("achieve", &[Joy]),
        ("achievement", &[Joy, Surprise]),
        ("acrid", &[Disgust]),
        ("admirable", &[Joy]),
        ("admiration", &[Joy]),
        ("admire", &[Joy]),
        ("adorable", &[Joy]),
        ("adore", &[Joy]),
        ("adventure", &[Joy, Surprise]),
        ("adventurous", &[Joy, Surprise]),
        ("affection", &[Joy]),
        ("affectionate", &[Joy]),
        ("afraid", &[Fear]),
        ("aggravate", &[Anger]),
        ("aggression", &[Anger]),
        ("aggressive", &[Anger, Fear]),
        ("aghast", &[Fear, Surprise, Disgust]),
        ("agitate", &[Anger, Fear]),
        ("agitated", &[Anger, Fear]),
        ("agony", &[Sadness, Fear]),
        ("agree", &[Joy]),
        ("agreeable", &[Joy]),
        ("alarm", &[Fear, Surprise]),
        ("alarmed", &[Fear, Surprise]),
        ("alarming", &[Fear]),
        ("alienate", &[Sadness, Anger]),
        ("alienated", &[Sadness]),
        ("alive", &[Joy]),
        ("alluring", &[Joy, Surprise]),
        ("alone", &[Sadness, Fear]),
        ("amaze", &[Surprise, Joy]),
        ("amazed", &[Surprise, Joy]),
        ("amazing", &[Surprise, Joy]),
        ("ambush", &[Fear, Surprise]),
        ("amusement", &[Joy, Surprise]),
        ("anger", &[Anger]),
        ("angry", &[Anger]),
        ("anguish", &[Sadness, Fear]),
        ("annihilate", &[Anger, Fear]),
        ("annoy", &[Anger]),
        ("annoyed", &[Anger]),
        ("annoying", &[Anger, Disgust]),
        ("antagonize", &[Anger]),
        ("anxiety", &[Fear]),
        ("anxious", &[Fear]),
        ("apathy", &[Sadness]),
        ("apocalypse", &[Fear, Sadness]),
        ("appall", &[Disgust, Fear]),
        ("appalled", &[Disgust, Surprise]),
        ("appalling", &[Disgust, Anger]),
        ("appreciate", &[Joy]),
        ("appreciation", &[Joy]),
        ("apprehension", &[Fear]),
        ("apprehensive", &[Fear]),
        ("assault", &[Anger, Fear]),
        ("astonish", &[Surprise]),
        ("astonished", &[Surprise]),
        ("astonishing", &[Surprise]),
        ("atrocious", &[Anger, Disgust]),
        ("atrocity", &[Anger, Disgust, Fear]),
        ("attack", &[Anger, Fear]),
        ("aversion", &[Disgust]),
        ("avoid", &[Fear]),
        ("awe", &[Surprise, Fear]),
        ("awesome", &[Joy, Surprise]),
        ("awful", &[Disgust, Sadness, Fear]),
        // ===== B =====
        ("baffle", &[Surprise]),
        ("baffled", &[Surprise]),
        ("ban", &[Anger, Sadness]),
        ("banish", &[Sadness, Anger]),
        ("bankrupt", &[Sadness, Fear]),
        ("barbaric", &[Anger, Disgust, Fear]),
        ("battle", &[Anger, Fear]),
        ("battlefield", &[Anger, Fear]),
        ("beautiful", &[Joy]),
        ("beauty", &[Joy]),
        ("befuddle", &[Surprise]),
        ("beg", &[Sadness, Fear]),
        ("belittle", &[Anger, Sadness]),
        ("beloved", &[Joy]),
        ("bemused", &[Surprise]),
        ("benevolent", &[Joy]),
        ("bereave", &[Sadness]),
        ("bereaved", &[Sadness]),
        ("bereavement", &[Sadness]),
        ("betray", &[Anger, Sadness]),
        ("betrayal", &[Anger, Sadness]),
        ("bewail", &[Sadness]),
        ("bewilder", &[Surprise]),
        ("bewildered", &[Surprise]),
        ("bitter", &[Anger, Sadness]),
        ("bitterness", &[Anger, Sadness]),
        ("bizarre", &[Surprise]),
        ("bleak", &[Sadness]),
        ("bless", &[Joy]),
        ("blessed", &[Joy]),
        ("blessing", &[Joy]),
        ("bliss", &[Joy]),
        ("blissful", &[Joy]),
        ("bloom", &[Joy]),
        ("blossom", &[Joy]),
        ("boil", &[Anger]),
        ("bold", &[Joy]),
        ("bomb", &[Fear, Anger]),
        ("bore", &[Sadness, Disgust]),
        ("bored", &[Sadness]),
        ("boredom", &[Sadness]),
        ("brave", &[Joy]),
        ("bravery", &[Joy]),
        ("break", &[Sadness, Anger]),
        ("breakthrough", &[Joy, Surprise]),
        ("bright", &[Joy]),
        ("brilliant", &[Joy, Surprise]),
        ("broken", &[Sadness]),
        ("brood", &[Sadness, Anger]),
        ("brutal", &[Anger, Fear, Disgust]),
        ("brutality", &[Anger, Disgust, Fear]),
        ("bully", &[Anger, Fear]),
        ("burden", &[Sadness]),
        ("burial", &[Sadness]),
        ("bury", &[Sadness]),
        // ===== C =====
        ("cage", &[Fear, Sadness]),
        ("calamity", &[Sadness, Fear]),
        ("calm", &[Joy]),
        ("captivate", &[Joy, Surprise]),
        ("captivating", &[Joy, Surprise]),
        ("care", &[Joy]),
        ("carefree", &[Joy]),
        ("caring", &[Joy]),
        ("catastrophe", &[Fear, Sadness]),
        ("catastrophic", &[Fear, Sadness]),
        ("caution", &[Fear]),
        ("cautious", &[Fear]),
        ("celebrate", &[Joy]),
        ("celebration", &[Joy]),
        ("chagrin", &[Sadness, Anger]),
        ("chaos", &[Fear, Anger]),
        ("chaotic", &[Fear, Anger]),
        ("charm", &[Joy]),
        ("charming", &[Joy]),
        ("cheat", &[Anger, Disgust]),
        ("cheer", &[Joy]),
        ("cheerful", &[Joy]),
        ("cheerfulness", &[Joy]),
        ("cherish", &[Joy]),
        ("clash", &[Anger]),
        ("cling", &[Fear, Sadness]),
        ("coerce", &[Anger, Fear]),
        ("coercion", &[Anger, Fear]),
        ("collapse", &[Sadness, Fear]),
        ("combat", &[Anger, Fear]),
        ("comfort", &[Joy]),
        ("comfortable", &[Joy]),
        ("commend", &[Joy]),
        ("compassion", &[Joy, Sadness]),
        ("compassionate", &[Joy]),
        ("compel", &[Anger, Fear]),
        ("condemn", &[Anger]),
        ("condemnation", &[Anger, Disgust]),
        ("confound", &[Surprise]),
        ("confuse", &[Surprise]),
        ("confused", &[Surprise, Fear]),
        ("confusion", &[Surprise, Fear]),
        ("conquer", &[Joy, Anger]),
        ("conspiracy", &[Fear, Anger]),
        ("contaminate", &[Disgust]),
        ("contaminated", &[Disgust]),
        ("contamination", &[Disgust, Fear]),
        ("contempt", &[Anger, Disgust]),
        ("contemptuous", &[Anger, Disgust]),
        ("content", &[Joy]),
        ("contented", &[Joy]),
        ("contentment", &[Joy]),
        ("convict", &[Sadness, Fear]),
        ("cordial", &[Joy]),
        ("corpse", &[Fear, Sadness, Disgust]),
        ("corrupt", &[Anger, Disgust]),
        ("corruption", &[Anger, Disgust]),
        ("courage", &[Joy]),
        ("courageous", &[Joy]),
        ("courteous", &[Joy]),
        ("cower", &[Fear]),
        ("cozy", &[Joy]),
        ("crash", &[Fear, Surprise]),
        ("creative", &[Joy]),
        ("creep", &[Fear, Disgust]),
        ("creepy", &[Fear, Disgust]),
        ("crime", &[Anger, Fear]),
        ("criminal", &[Anger, Fear, Disgust]),
        ("crisis", &[Fear]),
        ("cruel", &[Anger, Disgust]),
        ("cruelty", &[Anger, Disgust]),
        ("crumble", &[Sadness]),
        ("crush", &[Anger, Sadness]),
        ("crushed", &[Sadness]),
        ("cry", &[Sadness]),
        ("curious", &[Surprise]),
        ("curse", &[Anger]),
        ("cursed", &[Anger, Sadness]),
        // ===== D =====
        ("damage", &[Anger, Sadness]),
        ("damn", &[Anger]),
        ("damned", &[Anger, Sadness]),
        ("danger", &[Fear]),
        ("dangerous", &[Fear]),
        ("dare", &[Fear, Joy]),
        ("dark", &[Sadness, Fear]),
        ("darkness", &[Sadness, Fear]),
        ("daze", &[Surprise]),
        ("dazed", &[Surprise]),
        ("dead", &[Sadness, Fear]),
        ("deadly", &[Fear]),
        ("death", &[Sadness, Fear]),
        ("decay", &[Disgust, Sadness]),
        ("deceit", &[Anger, Disgust]),
        ("deceitful", &[Anger, Disgust]),
        ("deceive", &[Anger]),
        ("decompose", &[Disgust]),
        ("defeat", &[Sadness]),
        ("defeated", &[Sadness]),
        ("defile", &[Disgust, Anger]),
        ("degrade", &[Anger, Disgust, Sadness]),
        ("deject", &[Sadness]),
        ("dejected", &[Sadness]),
        ("delight", &[Joy]),
        ("delighted", &[Joy]),
        ("delightful", &[Joy]),
        ("demolish", &[Anger]),
        ("demon", &[Fear, Anger]),
        ("demoralize", &[Sadness]),
        ("denial", &[Sadness, Anger]),
        ("deplete", &[Sadness]),
        ("deplore", &[Anger, Disgust]),
        ("depressed", &[Sadness]),
        ("depression", &[Sadness]),
        ("deprive", &[Sadness, Anger]),
        ("deride", &[Anger, Disgust]),
        ("derision", &[Anger, Disgust]),
        ("desecrate", &[Anger, Disgust]),
        ("desert", &[Sadness]),
        ("deserted", &[Sadness, Fear]),
        ("desolate", &[Sadness]),
        ("desolation", &[Sadness]),
        ("despair", &[Sadness, Fear]),
        ("desperate", &[Fear, Sadness]),
        ("desperation", &[Fear, Sadness]),
        ("despicable", &[Anger, Disgust]),
        ("despise", &[Anger, Disgust]),
        ("destitute", &[Sadness]),
        ("destroy", &[Anger]),
        ("destruction", &[Anger, Fear]),
        ("destructive", &[Anger]),
        ("detest", &[Anger, Disgust]),
        ("detestable", &[Anger, Disgust]),
        ("devastate", &[Sadness]),
        ("devastated", &[Sadness]),
        ("devastating", &[Sadness, Fear]),
        ("devastation", &[Sadness, Fear]),
        ("devious", &[Anger, Disgust]),
        ("devote", &[Joy]),
        ("devoted", &[Joy]),
        ("devotion", &[Joy]),
        ("dictator", &[Anger, Fear]),
        ("die", &[Sadness, Fear]),
        ("dignified", &[Joy]),
        ("dignity", &[Joy]),
        ("dire", &[Fear, Sadness]),
        ("dirty", &[Disgust]),
        ("disappoint", &[Sadness]),
        ("disappointed", &[Sadness]),
        ("disappointment", &[Sadness]),
        ("disaster", &[Fear, Sadness]),
        ("disastrous", &[Fear, Sadness]),
        ("disbelief", &[Surprise]),
        ("discomfort", &[Sadness, Disgust]),
        ("discover", &[Surprise, Joy]),
        ("discovery", &[Surprise, Joy]),
        ("discriminate", &[Anger, Disgust]),
        ("discrimination", &[Anger, Sadness]),
        ("disease", &[Fear, Disgust, Sadness]),
        ("disgrace", &[Sadness, Anger]),
        ("disgraceful", &[Anger, Disgust]),
        ("disgusted", &[Disgust]),
        ("disgusting", &[Disgust]),
        ("disheartened", &[Sadness]),
        ("dishonest", &[Anger, Disgust]),
        ("dislike", &[Anger, Disgust]),
        ("dismal", &[Sadness]),
        ("dismay", &[Sadness, Fear]),
        ("dismiss", &[Sadness, Anger]),
        ("disorder", &[Fear]),
        ("displace", &[Sadness, Fear]),
        ("displeasure", &[Anger]),
        ("disrespect", &[Anger]),
        ("distaste", &[Disgust]),
        ("distasteful", &[Disgust]),
        ("distress", &[Sadness, Fear]),
        ("distressed", &[Sadness, Fear]),
        ("distrust", &[Fear, Anger]),
        ("disturb", &[Fear, Anger]),
        ("disturbed", &[Fear]),
        ("disturbing", &[Fear, Disgust]),
        ("divine", &[Joy]),
        ("dominate", &[Anger, Fear]),
        ("doom", &[Fear, Sadness]),
        ("doomed", &[Fear, Sadness]),
        ("doubt", &[Fear]),
        ("doubtful", &[Fear, Sadness]),
        ("dread", &[Fear]),
        ("dreadful", &[Fear, Disgust]),
        ("dreary", &[Sadness]),
        ("drown", &[Fear, Sadness]),
        ("dungeon", &[Fear, Sadness]),
        ("dying", &[Sadness, Fear]),
        // ===== E =====
        ("eager", &[Joy]),
        ("earnest", &[Joy]),
        ("ease", &[Joy]),
        ("ecstasy", &[Joy]),
        ("ecstatic", &[Joy]),
        ("eerie", &[Fear]),
        ("elate", &[Joy]),
        ("elated", &[Joy]),
        ("elegant", &[Joy]),
        ("embarrass", &[Sadness, Fear]),
        ("embarrassed", &[Sadness]),
        ("embarrassment", &[Sadness]),
        ("embrace", &[Joy]),
        ("emergency", &[Fear]),
        ("empathy", &[Joy, Sadness]),
        ("empower", &[Joy]),
        ("empty", &[Sadness]),
        ("enchant", &[Joy, Surprise]),
        ("enchanted", &[Joy, Surprise]),
        ("enchanting", &[Joy, Surprise]),
        ("encourage", &[Joy]),
        ("encouragement", &[Joy]),
        ("endanger", &[Fear]),
        ("endear", &[Joy]),
        ("endure", &[Sadness]),
        ("enemy", &[Anger, Fear]),
        ("energetic", &[Joy]),
        ("engage", &[Joy]),
        ("enjoy", &[Joy]),
        ("enjoyable", &[Joy]),
        ("enjoyment", &[Joy]),
        ("enlighten", &[Joy, Surprise]),
        ("enormous", &[Surprise]),
        ("enrage", &[Anger]),
        ("enraged", &[Anger]),
        ("enthuse", &[Joy]),
        ("enthusiasm", &[Joy]),
        ("enthusiastic", &[Joy]),
        ("envious", &[Anger, Sadness]),
        ("envy", &[Anger, Sadness]),
        ("epidemic", &[Fear, Sadness]),
        ("erupt", &[Anger, Surprise]),
        ("eruption", &[Anger, Surprise, Fear]),
        ("escape", &[Fear]),
        ("esteem", &[Joy]),
        ("euphoria", &[Joy]),
        ("euphoric", &[Joy]),
        ("evade", &[Fear]),
        ("evil", &[Anger, Fear, Disgust]),
        ("exasperate", &[Anger]),
        ("excellent", &[Joy]),
        ("exceptional", &[Joy, Surprise]),
        ("excite", &[Joy, Surprise]),
        ("excited", &[Joy, Surprise]),
        ("excitement", &[Joy, Surprise]),
        ("exciting", &[Joy, Surprise]),
        ("exclude", &[Sadness, Anger]),
        ("excruciating", &[Sadness, Fear]),
        ("exhaust", &[Sadness]),
        ("exhausted", &[Sadness]),
        ("exile", &[Sadness, Fear]),
        ("exploit", &[Anger]),
        ("exploitation", &[Anger, Disgust]),
        ("explode", &[Anger, Fear, Surprise]),
        ("explosion", &[Fear, Surprise]),
        ("expose", &[Fear, Surprise]),
        ("exposed", &[Fear]),
        ("extraordinary", &[Surprise, Joy]),
        ("exuberant", &[Joy]),
        // ===== F =====
        ("fabulous", &[Joy]),
        ("fade", &[Sadness]),
        ("fail", &[Sadness]),
        ("failure", &[Sadness]),
        ("faint", &[Fear, Surprise]),
        ("faith", &[Joy]),
        ("faithful", &[Joy]),
        ("fame", &[Joy]),
        ("famine", &[Sadness, Fear]),
        ("famous", &[Joy]),
        ("fantastic", &[Joy, Surprise]),
        ("fascinate", &[Surprise, Joy]),
        ("fascinated", &[Surprise, Joy]),
        ("fascinating", &[Surprise, Joy]),
        ("fatal", &[Fear, Sadness]),
        ("fate", &[Fear]),
        ("fatigue", &[Sadness]),
        ("fault", &[Anger, Sadness]),
        ("favor", &[Joy]),
        ("favorable", &[Joy]),
        ("favorite", &[Joy]),
        ("fear", &[Fear]),
        ("fearful", &[Fear]),
        ("fearless", &[Joy]),
        ("ferocious", &[Anger, Fear]),
        ("fertile", &[Joy]),
        ("festive", &[Joy]),
        ("feud", &[Anger]),
        ("fiend", &[Fear, Anger, Disgust]),
        ("fierce", &[Anger, Fear]),
        ("fight", &[Anger]),
        ("filth", &[Disgust]),
        ("filthy", &[Disgust]),
        ("fine", &[Joy]),
        ("flee", &[Fear]),
        ("flinch", &[Fear]),
        ("flourish", &[Joy]),
        ("fond", &[Joy]),
        ("fondness", &[Joy]),
        ("fool", &[Anger, Sadness]),
        ("foolish", &[Sadness, Anger]),
        ("forbid", &[Anger, Fear]),
        ("force", &[Anger, Fear]),
        ("forgive", &[Joy]),
        ("forgiveness", &[Joy]),
        ("forlorn", &[Sadness]),
        ("forsake", &[Sadness, Anger]),
        ("forsaken", &[Sadness]),
        ("fortune", &[Joy]),
        ("fortunate", &[Joy]),
        ("foul", &[Disgust]),
        ("fragile", &[Fear, Sadness]),
        ("frail", &[Fear, Sadness]),
        ("frantic", &[Fear]),
        ("fraud", &[Anger, Disgust]),
        ("free", &[Joy]),
        ("freedom", &[Joy]),
        ("freeze", &[Fear]),
        ("frenzy", &[Fear, Anger]),
        ("fret", &[Fear]),
        ("friend", &[Joy]),
        ("friendly", &[Joy]),
        ("friendship", &[Joy]),
        ("fright", &[Fear]),
        ("frighten", &[Fear]),
        ("frightened", &[Fear]),
        ("frightening", &[Fear]),
        ("frustrate", &[Anger]),
        ("frustrated", &[Anger]),
        ("frustration", &[Anger]),
        ("fulfill", &[Joy]),
        ("fulfilled", &[Joy]),
        ("fun", &[Joy]),
        ("funeral", &[Sadness]),
        ("furious", &[Anger]),
        ("fury", &[Anger]),
        ("futile", &[Sadness]),
        // ===== G =====
        ("gag", &[Disgust]),
        ("gallant", &[Joy]),
        ("generous", &[Joy]),
        ("generosity", &[Joy]),
        ("gentle", &[Joy]),
        ("genuine", &[Joy]),
        ("ghastly", &[Fear, Disgust]),
        ("glad", &[Joy]),
        ("gladness", &[Joy]),
        ("glee", &[Joy]),
        ("gleeful", &[Joy]),
        ("gloom", &[Sadness]),
        ("gloomy", &[Sadness]),
        ("glorious", &[Joy]),
        ("glory", &[Joy]),
        ("glum", &[Sadness]),
        ("gnaw", &[Fear, Anger]),
        ("gone", &[Sadness]),
        ("good", &[Joy]),
        ("goodness", &[Joy]),
        ("gorgeous", &[Joy]),
        ("grace", &[Joy]),
        ("graceful", &[Joy]),
        ("gracious", &[Joy]),
        ("grand", &[Joy]),
        ("grateful", &[Joy]),
        ("gratitude", &[Joy]),
        ("grave", &[Sadness, Fear]),
        ("greed", &[Anger, Disgust]),
        ("greedy", &[Anger, Disgust]),
        ("grief", &[Sadness]),
        ("grieve", &[Sadness]),
        ("grievous", &[Sadness]),
        ("grim", &[Sadness, Fear]),
        ("grin", &[Joy]),
        ("groan", &[Sadness]),
        ("gross", &[Disgust]),
        ("grotesque", &[Disgust]),
        ("grow", &[Joy]),
        ("growl", &[Anger]),
        ("grudge", &[Anger]),
        ("gruesome", &[Fear, Disgust]),
        ("grumpy", &[Anger, Sadness]),
        ("guilt", &[Sadness]),
        ("guilty", &[Sadness, Fear]),
        // ===== H =====
        ("happiness", &[Joy]),
        ("happy", &[Joy]),
        ("harass", &[Anger, Fear]),
        ("harassment", &[Anger, Fear]),
        ("hardship", &[Sadness]),
        ("harm", &[Anger, Fear]),
        ("harmful", &[Anger, Fear]),
        ("harmony", &[Joy]),
        ("harsh", &[Anger]),
        ("hate", &[Anger, Disgust]),
        ("hateful", &[Anger, Disgust]),
        ("hatred", &[Anger, Disgust]),
        ("haunt", &[Fear]),
        ("haunted", &[Fear, Sadness]),
        ("haven", &[Joy]),
        ("hazard", &[Fear]),
        ("hazardous", &[Fear]),
        ("heal", &[Joy]),
        ("healing", &[Joy]),
        ("health", &[Joy]),
        ("healthy", &[Joy]),
        ("heart", &[Joy]),
        ("heartbreak", &[Sadness]),
        ("heartbroken", &[Sadness]),
        ("heartfelt", &[Joy]),
        ("heartless", &[Anger, Sadness]),
        ("heartwarming", &[Joy]),
        ("heaven", &[Joy]),
        ("heavenly", &[Joy]),
        ("hell", &[Fear, Anger, Sadness]),
        ("hellish", &[Fear, Anger]),
        ("help", &[Joy]),
        ("helpful", &[Joy]),
        ("helpless", &[Fear, Sadness]),
        ("helplessness", &[Fear, Sadness]),
        ("hero", &[Joy]),
        ("heroic", &[Joy]),
        ("heroism", &[Joy]),
        ("hesitate", &[Fear]),
        ("hideous", &[Disgust, Fear]),
        ("hide", &[Fear]),
        ("hilarious", &[Joy, Surprise]),
        ("hit", &[Anger]),
        ("hollow", &[Sadness]),
        ("holy", &[Joy]),
        ("home", &[Joy]),
        ("honest", &[Joy]),
        ("honor", &[Joy]),
        ("hope", &[Joy]),
        ("hopeful", &[Joy]),
        ("hopeless", &[Sadness, Fear]),
        ("hopelessness", &[Sadness, Fear]),
        ("horrible", &[Disgust, Fear]),
        ("horrific", &[Fear, Disgust]),
        ("horrified", &[Fear, Disgust]),
        ("horrify", &[Fear, Disgust]),
        ("horror", &[Fear]),
        ("hospitable", &[Joy]),
        ("hostile", &[Anger]),
        ("hostility", &[Anger]),
        ("howl", &[Sadness, Fear]),
        ("hug", &[Joy]),
        ("humble", &[Joy]),
        ("humiliate", &[Anger, Sadness]),
        ("humiliated", &[Sadness, Anger]),
        ("humiliation", &[Sadness, Anger]),
        ("hunger", &[Sadness]),
        ("hungry", &[Sadness]),
        ("hurt", &[Sadness, Anger]),
        ("hurtful", &[Anger, Sadness]),
        ("hysteria", &[Fear]),
        ("hysterical", &[Fear, Surprise]),
        // ===== I =====
        ("ideal", &[Joy]),
        ("idolize", &[Joy]),
        ("ignore", &[Sadness, Anger]),
        ("ill", &[Sadness, Disgust]),
        ("illuminate", &[Joy, Surprise]),
        ("illustrious", &[Joy]),
        ("immoral", &[Anger, Disgust]),
        ("impatient", &[Anger]),
        ("imprison", &[Fear, Sadness]),
        ("imprisoned", &[Fear, Sadness]),
        ("impressive", &[Joy, Surprise]),
        ("incredible", &[Surprise, Joy]),
        ("incredulous", &[Surprise]),
        ("indignant", &[Anger]),
        ("indignation", &[Anger]),
        ("infect", &[Disgust, Fear]),
        ("infection", &[Disgust, Fear]),
        ("inferior", &[Sadness]),
        ("inflict", &[Anger]),
        ("infuriate", &[Anger]),
        ("infuriated", &[Anger]),
        ("ingenious", &[Joy, Surprise]),
        ("inhuman", &[Anger, Disgust]),
        ("injure", &[Anger, Sadness]),
        ("injury", &[Sadness, Fear]),
        ("injustice", &[Anger, Sadness]),
        ("innocent", &[Joy]),
        ("innovate", &[Joy, Surprise]),
        ("innovation", &[Joy, Surprise]),
        ("insane", &[Fear, Surprise]),
        ("insecure", &[Fear, Sadness]),
        ("insensitive", &[Anger]),
        ("inspire", &[Joy]),
        ("inspired", &[Joy]),
        ("inspiring", &[Joy]),
        ("insult", &[Anger]),
        ("insulted", &[Anger, Sadness]),
        ("insulting", &[Anger]),
        ("integrity", &[Joy]),
        ("intense", &[Fear, Surprise]),
        ("interest", &[Joy, Surprise]),
        ("interesting", &[Joy, Surprise]),
        ("intimidate", &[Fear, Anger]),
        ("intimidated", &[Fear]),
        ("intimidating", &[Fear]),
        ("intrigue", &[Surprise]),
        ("intriguing", &[Surprise]),
        ("invade", &[Fear, Anger]),
        ("invasion", &[Fear, Anger]),
        ("invent", &[Joy, Surprise]),
        ("invincible", &[Joy]),
        ("irate", &[Anger]),
        ("irritable", &[Anger]),
        ("irritate", &[Anger]),
        ("irritated", &[Anger]),
        ("isolate", &[Sadness]),
        ("isolated", &[Sadness, Fear]),
        ("isolation", &[Sadness, Fear]),
        // ===== J =====
        ("jail", &[Sadness, Fear]),
        ("jealous", &[Anger, Sadness]),
        ("jealousy", &[Anger, Sadness]),
        ("jeopardize", &[Fear]),
        ("jeopardy", &[Fear]),
        ("jest", &[Joy]),
        ("jewel", &[Joy]),
        ("jolt", &[Surprise, Fear]),
        ("jolly", &[Joy]),
        ("jovial", &[Joy]),
        ("joy", &[Joy]),
        ("joyful", &[Joy]),
        ("joyous", &[Joy]),
        ("jubilant", &[Joy]),
        ("jubilation", &[Joy]),
        ("judge", &[Anger]),
        ("just", &[Joy]),
        ("justice", &[Joy]),
        // ===== K =====
        ("keen", &[Joy]),
        ("kick", &[Anger]),
        ("kidnap", &[Fear, Anger]),
        ("kill", &[Anger, Fear]),
        ("killer", &[Fear, Anger]),
        ("kind", &[Joy]),
        ("kindle", &[Joy]),
        ("kindness", &[Joy]),
        ("kiss", &[Joy]),
        // ===== L =====
        ("lack", &[Sadness]),
        ("lament", &[Sadness]),
        ("laugh", &[Joy]),
        ("laughter", &[Joy]),
        ("lavish", &[Joy]),
        ("lazy", &[Disgust, Anger]),
        ("lethal", &[Fear]),
        ("liberate", &[Joy]),
        ("liberty", &[Joy]),
        ("lie", &[Anger, Disgust]),
        ("lively", &[Joy]),
        ("livid", &[Anger]),
        ("loathe", &[Anger, Disgust]),
        ("loathing", &[Anger, Disgust]),
        ("loathsome", &[Disgust]),
        ("lonely", &[Sadness]),
        ("lonesome", &[Sadness]),
        ("longing", &[Sadness]),
        ("lose", &[Sadness]),
        ("loss", &[Sadness]),
        ("lost", &[Sadness, Fear]),
        ("love", &[Joy]),
        ("loved", &[Joy]),
        ("lovely", &[Joy]),
        ("loving", &[Joy]),
        ("loyal", &[Joy]),
        ("loyalty", &[Joy]),
        ("luck", &[Joy]),
        ("lucky", &[Joy]),
        ("lurk", &[Fear]),
        // ===== M =====
        ("mad", &[Anger]),
        ("madness", &[Anger, Fear]),
        ("magic", &[Joy, Surprise]),
        ("magical", &[Joy, Surprise]),
        ("magnificent", &[Joy]),
        ("majestic", &[Joy, Surprise]),
        ("malice", &[Anger, Disgust]),
        ("malicious", &[Anger, Disgust]),
        ("manipulate", &[Anger, Disgust]),
        ("manipulation", &[Anger, Disgust]),
        ("marvelous", &[Joy, Surprise]),
        ("massacre", &[Fear, Anger, Disgust]),
        ("mean", &[Anger]),
        ("melancholy", &[Sadness]),
        ("menace", &[Fear, Anger]),
        ("menacing", &[Fear, Anger]),
        ("mercy", &[Joy, Sadness]),
        ("merry", &[Joy]),
        ("mess", &[Anger, Disgust]),
        ("messy", &[Disgust]),
        ("mingle", &[Joy]),
        ("miracle", &[Joy, Surprise]),
        ("miraculous", &[Joy, Surprise]),
        ("mirth", &[Joy]),
        ("mischief", &[Joy, Anger]),
        ("miserable", &[Sadness]),
        ("misery", &[Sadness]),
        ("misfortune", &[Sadness]),
        ("miss", &[Sadness]),
        ("mistake", &[Sadness]),
        ("mistrust", &[Fear, Anger]),
        ("mock", &[Anger, Disgust]),
        ("mockery", &[Anger, Disgust]),
        ("molest", &[Anger, Fear, Disgust]),
        ("monster", &[Fear, Disgust]),
        ("monstrous", &[Fear, Disgust]),
        ("mood", &[Sadness]),
        ("moody", &[Sadness, Anger]),
        ("morbid", &[Fear, Disgust]),
        ("morose", &[Sadness]),
        ("mourn", &[Sadness]),
        ("mournful", &[Sadness]),
        ("mourning", &[Sadness]),
        ("murder", &[Anger, Fear]),
        ("murderous", &[Anger, Fear]),
        ("mystery", &[Surprise]),
        ("mystify", &[Surprise]),
        // ===== N =====
        ("nasty", &[Disgust, Anger]),
        ("nausea", &[Disgust]),
        ("nauseate", &[Disgust]),
        ("nauseating", &[Disgust]),
        ("nauseous", &[Disgust]),
        ("neglect", &[Sadness, Anger]),
        ("neglected", &[Sadness]),
        ("nervous", &[Fear]),
        ("nice", &[Joy]),
        ("nightmare", &[Fear]),
        ("noble", &[Joy]),
        ("noxious", &[Disgust]),
        ("numb", &[Sadness]),
        ("nurture", &[Joy]),
        // ===== O =====
        ("obnoxious", &[Anger, Disgust]),
        ("obscene", &[Disgust, Anger]),
        ("obsess", &[Fear]),
        ("obsession", &[Fear]),
        ("obstacle", &[Anger, Sadness]),
        ("odd", &[Surprise]),
        ("offend", &[Anger]),
        ("offended", &[Anger]),
        ("offensive", &[Anger, Disgust]),
        ("ominous", &[Fear]),
        ("oppress", &[Anger, Fear, Sadness]),
        ("oppression", &[Anger, Sadness]),
        ("optimism", &[Joy]),
        ("optimistic", &[Joy]),
        ("ordeal", &[Sadness, Fear]),
        ("outcast", &[Sadness]),
        ("outcry", &[Anger, Sadness]),
        ("outrage", &[Anger]),
        ("outraged", &[Anger]),
        ("outrageous", &[Anger, Surprise]),
        ("outstanding", &[Joy]),
        ("overcome", &[Joy, Sadness]),
        ("overjoyed", &[Joy]),
        ("overwhelm", &[Surprise, Fear]),
        ("overwhelmed", &[Surprise, Fear, Sadness]),
        // ===== P =====
        ("pain", &[Sadness]),
        ("painful", &[Sadness]),
        ("panic", &[Fear]),
        ("panicked", &[Fear]),
        ("paradise", &[Joy]),
        ("paranoia", &[Fear]),
        ("paranoid", &[Fear]),
        ("passion", &[Joy]),
        ("passionate", &[Joy]),
        ("pathetic", &[Sadness, Disgust]),
        ("patience", &[Joy]),
        ("patient", &[Joy]),
        ("peace", &[Joy]),
        ("peaceful", &[Joy]),
        ("peculiar", &[Surprise]),
        ("peril", &[Fear]),
        ("perilous", &[Fear]),
        ("perplex", &[Surprise]),
        ("perplexed", &[Surprise]),
        ("persecute", &[Anger, Fear]),
        ("persecution", &[Anger, Fear, Sadness]),
        ("persevere", &[Joy]),
        ("pester", &[Anger]),
        ("petrified", &[Fear]),
        ("phobia", &[Fear]),
        ("pity", &[Sadness]),
        ("plague", &[Fear, Disgust]),
        ("pleasant", &[Joy]),
        ("please", &[Joy]),
        ("pleased", &[Joy]),
        ("pleasure", &[Joy]),
        ("plunder", &[Anger]),
        ("poison", &[Disgust, Fear]),
        ("poisonous", &[Disgust, Fear]),
        ("polite", &[Joy]),
        ("pollute", &[Disgust]),
        ("polluted", &[Disgust]),
        ("pollution", &[Disgust, Anger]),
        ("poor", &[Sadness]),
        ("positive", &[Joy]),
        ("poverty", &[Sadness]),
        ("power", &[Joy]),
        ("powerful", &[Joy]),
        ("powerless", &[Fear, Sadness]),
        ("praise", &[Joy]),
        ("precious", &[Joy]),
        ("predator", &[Fear]),
        ("prey", &[Fear]),
        ("pride", &[Joy]),
        ("prison", &[Fear, Sadness]),
        ("prisoner", &[Sadness, Fear]),
        ("privilege", &[Joy]),
        ("problem", &[Sadness, Anger]),
        ("progress", &[Joy]),
        ("promise", &[Joy]),
        ("prosperous", &[Joy]),
        ("prosper", &[Joy]),
        ("protect", &[Joy, Fear]),
        ("protection", &[Joy]),
        ("proud", &[Joy]),
        ("provoke", &[Anger]),
        ("provoked", &[Anger]),
        ("prowl", &[Fear]),
        ("punish", &[Anger]),
        ("punishment", &[Anger, Fear]),
        ("pure", &[Joy]),
        ("purity", &[Joy]),
        ("pursue", &[Fear]),
        ("putrid", &[Disgust]),
        ("puzzle", &[Surprise]),
        ("puzzled", &[Surprise]),
        ("puzzling", &[Surprise]),
        // ===== Q =====
        ("quarrel", &[Anger]),
        ("queasy", &[Disgust]),
        ("quiet", &[Joy]),
        // ===== R =====
        ("radiant", &[Joy]),
        ("rage", &[Anger]),
        ("rampant", &[Fear, Anger]),
        ("ransack", &[Anger]),
        ("rapture", &[Joy]),
        ("rare", &[Surprise]),
        ("rash", &[Anger]),
        ("ravage", &[Anger, Fear]),
        ("rebel", &[Anger]),
        ("rebellion", &[Anger]),
        ("reckless", &[Fear, Anger]),
        ("recoil", &[Fear, Disgust]),
        ("recover", &[Joy]),
        ("recovery", &[Joy]),
        ("redeem", &[Joy]),
        ("refresh", &[Joy]),
        ("refuge", &[Joy, Fear]),
        ("regret", &[Sadness]),
        ("regretful", &[Sadness]),
        ("reject", &[Sadness, Anger]),
        ("rejected", &[Sadness]),
        ("rejection", &[Sadness]),
        ("rejoice", &[Joy]),
        ("relax", &[Joy]),
        ("relaxed", &[Joy]),
        ("relief", &[Joy]),
        ("relieve", &[Joy]),
        ("remarkable", &[Surprise, Joy]),
        ("remorse", &[Sadness]),
        ("renew", &[Joy]),
        ("repel", &[Disgust]),
        ("repent", &[Sadness]),
        ("replenish", &[Joy]),
        ("repugnant", &[Disgust]),
        ("repulse", &[Disgust]),
        ("repulsive", &[Disgust]),
        ("rescue", &[Joy, Fear]),
        ("resentful", &[Anger]),
        ("resentment", &[Anger]),
        ("resign", &[Sadness]),
        ("resignation", &[Sadness]),
        ("resilient", &[Joy]),
        ("respect", &[Joy]),
        ("respectable", &[Joy]),
        ("rest", &[Joy]),
        ("restore", &[Joy]),
        ("restless", &[Fear]),
        ("retaliate", &[Anger]),
        ("retaliation", &[Anger]),
        ("retch", &[Disgust]),
        ("retreat", &[Fear, Sadness]),
        ("reveal", &[Surprise]),
        ("revelation", &[Surprise]),
        ("revenge", &[Anger]),
        ("revere", &[Joy]),
        ("revile", &[Anger, Disgust]),
        ("revive", &[Joy]),
        ("revolt", &[Anger, Disgust]),
        ("revolting", &[Disgust]),
        ("reward", &[Joy]),
        ("rich", &[Joy]),
        ("ridicule", &[Anger, Disgust]),
        ("ridiculous", &[Anger, Surprise]),
        ("righteous", &[Joy]),
        ("rigid", &[Anger]),
        ("riot", &[Anger, Fear]),
        ("risk", &[Fear]),
        ("risky", &[Fear]),
        ("rob", &[Anger, Fear]),
        ("rot", &[Disgust]),
        ("rotten", &[Disgust]),
        ("rude", &[Anger, Disgust]),
        ("ruin", &[Anger, Sadness]),
        ("ruinous", &[Sadness, Fear]),
        ("rumble", &[Fear]),
        ("ruthless", &[Anger, Fear]),
        // ===== S =====
        ("sacred", &[Joy]),
        ("sacrifice", &[Sadness]),
        ("sad", &[Sadness]),
        ("sadness", &[Sadness]),
        ("safe", &[Joy]),
        ("safety", &[Joy]),
        ("salvation", &[Joy]),
        ("sanctuary", &[Joy]),
        ("satisfied", &[Joy]),
        ("satisfy", &[Joy]),
        ("savage", &[Anger, Fear]),
        ("save", &[Joy]),
        ("scare", &[Fear]),
        ("scared", &[Fear]),
        ("scary", &[Fear]),
        ("scold", &[Anger]),
        ("scorn", &[Anger, Disgust]),
        ("scornful", &[Anger, Disgust]),
        ("scream", &[Fear]),
        ("seethe", &[Anger]),
        ("seething", &[Anger]),
        ("serene", &[Joy]),
        ("serenity", &[Joy]),
        ("severe", &[Fear, Anger]),
        ("shame", &[Sadness]),
        ("shameful", &[Sadness, Disgust]),
        ("shatter", &[Sadness]),
        ("shattered", &[Sadness]),
        ("shelter", &[Joy]),
        ("shimmer", &[Joy]),
        ("shiver", &[Fear]),
        ("shock", &[Surprise, Fear]),
        ("shocked", &[Surprise]),
        ("shocking", &[Surprise, Anger]),
        ("shout", &[Anger]),
        ("shriek", &[Fear]),
        ("shudder", &[Fear, Disgust]),
        ("shy", &[Fear]),
        ("sick", &[Disgust, Sadness]),
        ("sickening", &[Disgust]),
        ("sigh", &[Sadness]),
        ("sincere", &[Joy]),
        ("sinister", &[Fear]),
        ("slam", &[Anger]),
        ("slaughter", &[Anger, Fear, Disgust]),
        ("slave", &[Sadness, Anger]),
        ("slavery", &[Sadness, Anger]),
        ("slime", &[Disgust]),
        ("slimy", &[Disgust]),
        ("slump", &[Sadness]),
        ("smash", &[Anger]),
        ("smile", &[Joy]),
        ("smother", &[Fear]),
        ("snare", &[Fear]),
        ("sneer", &[Anger, Disgust]),
        ("sob", &[Sadness]),
        ("solemn", &[Sadness]),
        ("solitude", &[Sadness]),
        ("somber", &[Sadness]),
        ("soothe", &[Joy]),
        ("soothing", &[Joy]),
        ("sore", &[Sadness]),
        ("sorrow", &[Sadness]),
        ("sorrowful", &[Sadness]),
        ("sorry", &[Sadness]),
        ("soul", &[Joy]),
        ("sour", &[Disgust]),
        ("spectacular", &[Joy, Surprise]),
        ("spite", &[Anger]),
        ("spiteful", &[Anger]),
        ("splendid", &[Joy]),
        ("spoil", &[Disgust, Anger]),
        ("squalid", &[Disgust]),
        ("squirm", &[Disgust, Fear]),
        ("stab", &[Anger, Fear]),
        ("stagger", &[Surprise]),
        ("staggering", &[Surprise]),
        ("stale", &[Disgust]),
        ("startle", &[Surprise, Fear]),
        ("startled", &[Surprise, Fear]),
        ("startling", &[Surprise]),
        ("starve", &[Sadness]),
        ("steal", &[Anger]),
        ("stench", &[Disgust]),
        ("stink", &[Disgust]),
        ("stinking", &[Disgust]),
        ("storm", &[Fear, Anger]),
        ("strange", &[Surprise]),
        ("stranger", &[Fear, Surprise]),
        ("strength", &[Joy]),
        ("stress", &[Fear, Sadness]),
        ("strike", &[Anger]),
        ("strong", &[Joy]),
        ("struggle", &[Sadness, Fear]),
        ("stun", &[Surprise]),
        ("stunned", &[Surprise]),
        ("stunning", &[Surprise, Joy]),
        ("stupid", &[Anger, Disgust]),
        ("sublime", &[Joy, Surprise]),
        ("succeed", &[Joy]),
        ("success", &[Joy]),
        ("successful", &[Joy]),
        ("sudden", &[Surprise]),
        ("suffer", &[Sadness]),
        ("suffering", &[Sadness]),
        ("suffocate", &[Fear]),
        ("sulk", &[Sadness, Anger]),
        ("sunshine", &[Joy]),
        ("superb", &[Joy]),
        ("support", &[Joy]),
        ("supportive", &[Joy]),
        ("suppress", &[Anger, Sadness]),
        ("surrender", &[Sadness, Fear]),
        ("survive", &[Joy, Fear]),
        ("suspect", &[Fear]),
        ("suspicion", &[Fear]),
        ("suspicious", &[Fear]),
        ("sweet", &[Joy]),
        ("sympathy", &[Sadness, Joy]),
        // ===== T =====
        ("taint", &[Disgust]),
        ("tainted", &[Disgust]),
        ("talent", &[Joy]),
        ("talented", &[Joy]),
        ("tantrum", &[Anger]),
        ("tear", &[Sadness]),
        ("tease", &[Anger]),
        ("temper", &[Anger]),
        ("tender", &[Joy]),
        ("tenderness", &[Joy]),
        ("tense", &[Fear]),
        ("tension", &[Fear, Anger]),
        ("terrible", &[Fear, Sadness]),
        ("terrified", &[Fear]),
        ("terrify", &[Fear]),
        ("terrifying", &[Fear]),
        ("terror", &[Fear]),
        ("terrorize", &[Fear, Anger]),
        ("thankful", &[Joy]),
        ("thankfulness", &[Joy]),
        ("thankless", &[Sadness, Anger]),
        ("thief", &[Anger]),
        ("threat", &[Fear]),
        ("threaten", &[Fear, Anger]),
        ("threatened", &[Fear]),
        ("threatening", &[Fear, Anger]),
        ("thrill", &[Joy, Surprise]),
        ("thrilled", &[Joy, Surprise]),
        ("thrilling", &[Joy, Surprise]),
        ("thrive", &[Joy]),
        ("thriving", &[Joy]),
        ("tomb", &[Sadness, Fear]),
        ("torment", &[Anger, Sadness, Fear]),
        ("tormented", &[Sadness, Fear]),
        ("torture", &[Anger, Fear, Sadness]),
        ("toxic", &[Disgust, Fear]),
        ("tragedy", &[Sadness]),
        ("tragic", &[Sadness]),
        ("tranquil", &[Joy]),
        ("tranquility", &[Joy]),
        ("trap", &[Fear]),
        ("trapped", &[Fear, Sadness]),
        ("trauma", &[Fear, Sadness]),
        ("traumatic", &[Fear, Sadness]),
        ("treacherous", &[Anger, Fear]),
        ("treachery", &[Anger]),
        ("treasure", &[Joy]),
        ("tremble", &[Fear]),
        ("tremendous", &[Surprise, Joy]),
        ("triumph", &[Joy]),
        ("triumphant", &[Joy]),
        ("trouble", &[Sadness, Fear]),
        ("troublesome", &[Anger]),
        ("trust", &[Joy]),
        ("trustworthy", &[Joy]),
        ("turmoil", &[Fear, Anger, Sadness]),
        ("tyranny", &[Anger, Fear]),
        ("tyrant", &[Anger, Fear]),
        // ===== U =====
        ("ugly", &[Disgust]),
        ("unbelievable", &[Surprise]),
        ("uncertain", &[Fear]),
        ("uncertainty", &[Fear]),
        ("uncomfortable", &[Sadness, Fear]),
        ("uncover", &[Surprise]),
        ("unexpected", &[Surprise]),
        ("unfair", &[Anger, Sadness]),
        ("unfortunate", &[Sadness]),
        ("unforeseen", &[Surprise]),
        ("unhappy", &[Sadness]),
        ("unique", &[Surprise, Joy]),
        ("united", &[Joy]),
        ("unity", &[Joy]),
        ("unjust", &[Anger]),
        ("unlucky", &[Sadness]),
        ("unpleasant", &[Disgust]),
        ("unrest", &[Fear, Anger]),
        ("unsafe", &[Fear]),
        ("unwanted", &[Sadness]),
        ("unworthy", &[Sadness]),
        ("upheaval", &[Fear, Surprise]),
        ("uplifting", &[Joy]),
        ("upset", &[Sadness, Anger]),
        ("uproar", &[Anger, Surprise]),
        ("useless", &[Sadness]),
        ("utopia", &[Joy]),
        // ===== V =====
        ("valiant", &[Joy]),
        ("valor", &[Joy]),
        ("valuable", &[Joy]),
        ("vanish", &[Sadness, Surprise]),
        ("vengeance", &[Anger]),
        ("vengeful", &[Anger]),
        ("venom", &[Anger, Disgust]),
        ("venomous", &[Anger, Disgust, Fear]),
        ("vibrant", &[Joy]),
        ("vicious", &[Anger, Fear]),
        ("victim", &[Sadness, Fear]),
        ("victimize", &[Anger, Sadness]),
        ("victorious", &[Joy]),
        ("victory", &[Joy]),
        ("vile", &[Disgust, Anger]),
        ("villain", &[Anger, Fear]),
        ("vindictive", &[Anger]),
        ("violate", &[Anger, Disgust]),
        ("violation", &[Anger, Disgust]),
        ("violence", &[Anger, Fear]),
        ("violent", &[Anger, Fear]),
        ("virtue", &[Joy]),
        ("virtuous", &[Joy]),
        ("vital", &[Joy]),
        ("void", &[Sadness]),
        ("volatile", &[Fear, Anger]),
        ("vomit", &[Disgust]),
        ("vulnerable", &[Fear, Sadness]),
        ("vulgar", &[Disgust, Anger]),
        // ===== W =====
        ("wail", &[Sadness]),
        ("war", &[Anger, Fear]),
        ("warm", &[Joy]),
        ("warmth", &[Joy]),
        ("warn", &[Fear]),
        ("warning", &[Fear]),
        ("warrior", &[Anger, Joy]),
        ("waste", &[Sadness, Disgust]),
        ("weak", &[Sadness, Fear]),
        ("weakness", &[Sadness, Fear]),
        ("wealth", &[Joy]),
        ("weapon", &[Fear, Anger]),
        ("weary", &[Sadness]),
        ("weep", &[Sadness]),
        ("weird", &[Surprise]),
        ("welcome", &[Joy]),
        ("welfare", &[Joy]),
        ("wicked", &[Anger, Disgust]),
        ("wild", &[Fear, Surprise]),
        ("willing", &[Joy]),
        ("win", &[Joy]),
        ("wisdom", &[Joy]),
        ("wise", &[Joy]),
        ("wish", &[Joy]),
        ("wither", &[Sadness]),
        ("withered", &[Sadness]),
        ("woeful", &[Sadness]),
        ("wonder", &[Surprise, Joy]),
        ("wonderful", &[Joy]),
        ("wondrous", &[Surprise, Joy]),
        ("worry", &[Fear]),
        ("worried", &[Fear]),
        ("worship", &[Joy]),
        ("worthless", &[Sadness]),
        ("worthy", &[Joy]),
        ("wound", &[Sadness, Anger]),
        ("wounded", &[Sadness]),
        ("wrath", &[Anger]),
        ("wreck", &[Anger, Sadness]),
        ("wretched", &[Sadness, Disgust]),
        ("wrong", &[Anger, Sadness]),
        // ===== X =====
        ("xenophobia", &[Fear, Anger, Disgust]),
        // ===== Y =====
        ("yearn", &[Sadness]),
        ("yearning", &[Sadness]),
        ("yell", &[Anger]),
        // ===== Z =====
        ("zeal", &[Joy]),
        ("zealot", &[Anger, Fear]),
        ("zealous", &[Joy, Anger]),
        ("zenith", &[Joy]),
        ("zest", &[Joy]),
        ("zombie", &[Fear, Disgust]),
    ];
    entries
        .iter()
        .map(|(word, emotions)| (*word, emotions.to_vec()))
        .collect()
});
