/// Hedging phrases that indicate uncertainty or tentativeness.
pub static HEDGING_PHRASES: &[&str] = &[
    "might",
    "perhaps",
    "maybe",
    "possibly",
    "probably",
    "i think",
    "i believe",
    "i guess",
    "i suppose",
    "it seems",
    "it appears",
    "sort of",
    "kind of",
    "somewhat",
    "arguably",
    "conceivably",
    "apparently",
    "presumably",
    "roughly",
    "in my opinion",
    "from my perspective",
    "as far as i know",
    "to some extent",
    "more or less",
    "not entirely",
    "i would say",
    "i feel like",
    "it could be",
    "tend to",
    "it seems like",
    "if i recall",
    "not necessarily",
    "to a degree",
];

/// Markers of formal register.
pub static FORMAL_MARKERS: &[&str] = &[
    "therefore",
    "furthermore",
    "moreover",
    "consequently",
    "nevertheless",
    "notwithstanding",
    "accordingly",
    "hence",
    "thus",
    "whereby",
    "wherein",
    "henceforth",
    "aforementioned",
    "subsequently",
    "preceding",
    "pursuant",
    "respective",
    "shall",
    "herein",
    "therein",
    "inasmuch",
    "insofar",
    "regarding",
    "pertaining",
    "constitutes",
    "stipulate",
    "facilitate",
    "endeavor",
    "utilize",
    "implement",
    "demonstrate",
    "indicate",
    "commence",
    "terminate",
    "acquisition",
    "methodology",
    "specification",
    "compliance",
    "infrastructure",
    "framework",
    "paradigm",
    "comprehensive",
    "substantive",
    "preliminary",
    "supplementary",
    "fundamental",
    "significant",
    "appropriate",
    "sufficient",
    "additional",
];

/// Markers of informal register (contractions, slang, casual language).
pub static INFORMAL_MARKERS: &[&str] = &[
    "gonna",
    "wanna",
    "gotta",
    "kinda",
    "sorta",
    "ain't",
    "can't",
    "won't",
    "don't",
    "doesn't",
    "isn't",
    "wasn't",
    "weren't",
    "shouldn't",
    "couldn't",
    "wouldn't",
    "haven't",
    "hasn't",
    "hadn't",
    "didn't",
    "it's",
    "that's",
    "there's",
    "here's",
    "what's",
    "who's",
    "let's",
    "i'm",
    "i've",
    "i'd",
    "i'll",
    "you're",
    "you've",
    "you'd",
    "you'll",
    "we're",
    "we've",
    "we'd",
    "we'll",
    "they're",
    "they've",
    "they'd",
    "they'll",
    "he's",
    "she's",
    "lol",
    "omg",
    "btw",
    "tbh",
    "imo",
    "idk",
    "nah",
    "yeah",
    "yep",
    "nope",
    "ok",
    "okay",
    "cool",
    "awesome",
    "stuff",
    "thing",
    "things",
    "basically",
    "literally",
    "actually",
    "seriously",
    "totally",
    "pretty much",
    "a lot",
    "lots of",
    "tons of",
    "bunch of",
    "hey",
    "hi",
    "yo",
    "dude",
    "guys",
    "like",
    "super",
    "way too",
    "no way",
];

/// Certainty modal verbs with confidence scores from 0.0 (uncertain) to 1.0 (certain).
pub static CERTAINTY_MODALS: &[(&str, f64)] = &[
    ("must", 0.95),
    ("will", 0.90),
    ("shall", 0.90),
    ("certainly", 0.95),
    ("definitely", 0.95),
    ("undoubtedly", 0.95),
    ("absolutely", 0.95),
    ("always", 0.90),
    ("never", 0.90),
    ("clearly", 0.85),
    ("obviously", 0.85),
    ("evidently", 0.80),
    ("surely", 0.85),
    ("indeed", 0.80),
    ("without doubt", 0.95),
    ("no question", 0.95),
    ("guaranteed", 0.95),
    ("inevitably", 0.90),
    ("unquestionably", 0.95),
    ("should", 0.70),
    ("would", 0.60),
    ("can", 0.65),
    ("could", 0.40),
    ("may", 0.35),
    ("might", 0.25),
    ("possibly", 0.25),
    ("perhaps", 0.20),
    ("maybe", 0.20),
    ("probably", 0.60),
    ("likely", 0.65),
    ("unlikely", 0.30),
    ("doubtful", 0.15),
    ("uncertain", 0.15),
    ("questionable", 0.15),
    ("seems", 0.40),
    ("appears", 0.40),
    ("suggests", 0.45),
    ("indicates", 0.55),
    ("confirms", 0.90),
    ("proves", 0.90),
    ("establishes", 0.85),
    ("verifies", 0.85),
];
